"""Utilities for managing station metadata exported in JSON format.

This class is designed to work with station data generated by station_pipeline.py
(the `export_data` output), where data is organized by year and station code.
"""

from __future__ import annotations

from typing import Any
import copy
import json
import os
import pprint as pp
import tempfile

from .ContaminantManagerJSON import ContaminantManagerJSON


class StationManagerJSON:
    """Manager for station metadata loaded from JSON or in-memory dictionaries.

    Expected structure:
        {
            "2019": {
                "4": {
                    "station_name": "...",
                    "contaminant_code": [1, 10, 110],
                    "contaminant_names": ["SO2", "PM10", "PM10"],
                    ...
                },
                ...
            },
            "2021": {
                ...
            }
        }
    """

    def __init__(
        self,
        file_path: str | None = None,
        station_data_by_year: dict[str, Any] | None = None,
        contaminant_manager: ContaminantManagerJSON | None = None,
    ) -> None:
        if file_path is None and station_data_by_year is None:
            raise ValueError("Either file_path or station_data_by_year must be provided.")

        if file_path is not None and station_data_by_year is not None:
            raise ValueError("Provide only one source: file_path or station_data_by_year.")

        self._stations_data_by_year: dict[str, Any] = {}

        if file_path is not None:
            with open(file_path, encoding="utf-8") as json_file:
                self._stations_data_by_year = json.load(json_file)
        else:
            self._stations_data_by_year = copy.deepcopy(station_data_by_year)

        self._contaminant_manager = contaminant_manager

    def __repr__(self) -> str:
        years = self.get_available_years()
        total_stations = sum(len(self._stations_data_by_year[str(y)]) for y in years)
        return (
            f"{self.__class__.__name__}("
            f"years={years}, "
            f"year_count={len(years)}, "
            f"station_entries={total_stations})"
        )

    @classmethod
    def from_pipeline_export_data(
        cls,
        export_data: dict[str, dict[str, Any]],
        contaminant_manager: ContaminantManagerJSON | None = None,
    ) -> "StationManagerJSON":
        """Build from the `export_data` object returned by run_station_pipeline."""
        return cls(station_data_by_year=export_data, contaminant_manager=contaminant_manager)

    def set_contaminant_manager(self, contaminant_manager: ContaminantManagerJSON) -> None:
        """Attach or replace the contaminant manager used for enrichment queries."""
        self._contaminant_manager = contaminant_manager

    def get_available_years(self) -> list[int]:
        """Return sorted list of available years."""
        years: list[int] = []
        for year_key in self._stations_data_by_year.keys():
            try:
                years.append(int(year_key))
            except ValueError:
                continue

        years.sort()
        return years

    def has_year(self, year: int) -> bool:
        """Check if a year exists in station data."""
        return str(year) in self._stations_data_by_year

    def get_station_ids(self, year: int | None = None) -> list[str]:
        """Return station ids for one year, or all unique ids across all years."""
        if year is not None:
            year_key = str(year)
            if year_key not in self._stations_data_by_year:
                return []
            return sorted(self._stations_data_by_year[year_key].keys())

        all_ids: set[str] = set()
        for station_data in self._stations_data_by_year.values():
            all_ids.update(station_data.keys())

        return sorted(all_ids)

    def has_station(self, station_id: str | int, year: int | None = None) -> bool:
        """Check if a station exists in a year or in any year."""
        station_key = str(station_id)

        if year is not None:
            year_key = str(year)
            return (
                year_key in self._stations_data_by_year
                and station_key in self._stations_data_by_year[year_key]
            )

        return any(
            station_key in self._stations_data_by_year[str(y)]
            for y in self.get_available_years()
        )

    def get_station_data(self, station_id: str | int, year: int) -> dict[str, Any] | None:
        """Return one station record for a specific year."""
        station_key = str(station_id)
        year_key = str(year)

        if year_key not in self._stations_data_by_year:
            return None

        station_data = self._stations_data_by_year[year_key].get(station_key)
        if station_data is None:
            return None

        return copy.deepcopy(station_data)

    def get_latest_station_data(self, station_id: str | int) -> dict[str, Any] | None:
        """Return the latest available record for a station across all years."""
        station_key = str(station_id)
        years_desc = sorted(self.get_available_years(), reverse=True)

        for year in years_desc:
            year_key = str(year)
            if station_key in self._stations_data_by_year[year_key]:
                result = copy.deepcopy(self._stations_data_by_year[year_key][station_key])
                result["year"] = year
                return result

        return None

    def get_station_contaminant_codes(self, station_id: str | int, year: int) -> list[int] | None:
        """Return contaminant codes measured by a station in a given year."""
        station_data = self.get_station_data(station_id, year)
        if station_data is None:
            return None

        codes = station_data.get("contaminant_code")
        if not isinstance(codes, list):
            return None

        parsed_codes: list[int] = []
        for code in codes:
            try:
                parsed_codes.append(int(float(code)))
            except (TypeError, ValueError):
                continue

        return parsed_codes

    def get_station_contaminant_metadata(
        self,
        station_id: str | int,
        year: int,
    ) -> list[dict[str, Any]] | None:
        """Return contaminant metadata for all contaminants measured by a station.

        Requires an attached ContaminantManagerJSON.
        """
        if self._contaminant_manager is None:
            raise ValueError(
                "No ContaminantManagerJSON configured. "
                "Use set_contaminant_manager(...) or pass it in __init__."
            )

        codes = self.get_station_contaminant_codes(station_id, year)
        if codes is None:
            return None

        metadata_items: list[dict[str, Any]] = []
        for code in codes:
            summary = self._contaminant_manager.get_metadata_summary_by_code(code)
            metadata_items.append(summary if summary is not None else {"code": code, "description": "UNKNOWN"})

        return metadata_items

    def get_stations_measuring_contaminant(self, contaminant_code: int, year: int) -> list[str]:
        """Return station ids that measure a given contaminant code in a year."""
        year_key = str(year)
        if year_key not in self._stations_data_by_year:
            return []

        target_code = int(contaminant_code)
        matched: list[str] = []

        for station_id, station_data in self._stations_data_by_year[year_key].items():
            codes = station_data.get("contaminant_code", [])
            if not isinstance(codes, list):
                continue

            parsed_codes: list[int] = []
            for code in codes:
                try:
                    parsed_codes.append(int(float(code)))
                except (TypeError, ValueError):
                    continue

            if target_code in parsed_codes:
                matched.append(station_id)

        matched.sort()
        return matched

    def get_all_data(self) -> dict[str, Any]:
        """Return a deep copy of all station data by year."""
        return copy.deepcopy(self._stations_data_by_year)


def _build_demo_station_data() -> dict[str, Any]:
    """Create deterministic sample station data for manual testing."""
    return {
        "2019": {
            "4": {
                "station_name": "Eixample",
                "location": "Carrer de Valencia",
                "latitude": 41.39,
                "longitude": 2.16,
                "contaminant_code": [1, 10, 110],
                "contaminant_names": ["SO2", "PM10", "PM10"],
            },
            "8": {
                "station_name": "Gracia",
                "location": "Travessera de Gracia",
                "latitude": 41.40,
                "longitude": 2.15,
                "contaminant_code": [6, 9],
                "contaminant_names": ["CO", "PM2_5"],
            },
        },
        "2021": {
            "4": {
                "station_name": "Eixample",
                "location": "Carrer de Valencia",
                "latitude": 41.39,
                "longitude": 2.16,
                "contaminant_code": [1, 10, 110, 8],
                "contaminant_names": ["SO2", "PM10", "PM10", "NO2"],
            },
            "11": {
                "station_name": "Sants",
                "location": "Carrer de Sants",
                "latitude": 41.37,
                "longitude": 2.14,
                "contaminant_code": [8, 9, 10],
                "contaminant_names": ["NO2", "PM2_5", "PM10"],
            },
        },
    }


def main() -> None:
    """Run a lightweight manual test for all public StationManagerJSON methods."""

    print("=" * 80)
    print("StationManagerJSON manual test")
    print("=" * 80)

    demo_data = _build_demo_station_data()

    print("\n1) Construct from in-memory data")
    station_manager = StationManagerJSON(station_data_by_year=demo_data)
    print(station_manager)

    print("\n2) Construct from file path")
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as tmp_file:
        json.dump(demo_data, tmp_file, indent=2)
        temp_path = tmp_file.name

    try:
        station_manager_from_file = StationManagerJSON(file_path=temp_path)
        print(station_manager_from_file)
    finally:
        os.unlink(temp_path)

    print("\n3) Build using from_pipeline_export_data")
    station_manager_from_pipeline = StationManagerJSON.from_pipeline_export_data(demo_data)
    print(station_manager_from_pipeline)

    print("\n4) get_available_years / has_year")
    years = station_manager.get_available_years()
    print("Available years:", years)
    print("Has year 2019:", station_manager.has_year(2019))
    print("Has year 2022:", station_manager.has_year(2022))

    print("\n5) get_station_ids / has_station")
    print("All station ids:", station_manager.get_station_ids())
    print("2019 station ids:", station_manager.get_station_ids(2019))
    print("Unknown year station ids:", station_manager.get_station_ids(2025))
    print("Has station '4' in any year:", station_manager.has_station("4"))
    print("Has station '8' in 2021:", station_manager.has_station("8", 2021))

    print("\n6) get_station_data / get_latest_station_data")
    pp.pprint(station_manager.get_station_data("4", 2019))
    pp.pprint(station_manager.get_station_data("999", 2019))
    pp.pprint(station_manager.get_latest_station_data("4"))
    pp.pprint(station_manager.get_latest_station_data("999"))

    print("\n7) get_station_contaminant_codes")
    print("Station 4, 2021:", station_manager.get_station_contaminant_codes("4", 2021))
    print("Station 999, 2021:", station_manager.get_station_contaminant_codes("999", 2021))

    print("\n8) get_station_contaminant_metadata without manager (expected error)")
    try:
        station_manager.get_station_contaminant_metadata("4", 2021)
    except ValueError as exc:
        print("Expected ValueError:", exc)

    print("\n9) set_contaminant_manager / get_station_contaminant_metadata")
    contaminants_json_path = "./../data/gold/contaminants/contaminants.json"
    if os.path.exists(contaminants_json_path):
        contaminant_manager = ContaminantManagerJSON(contaminants_json_path)
        station_manager.set_contaminant_manager(contaminant_manager)
        pp.pprint(station_manager.get_station_contaminant_metadata("4", 2021))
    else:
        print("Skipped integration test: contaminants JSON file not found at", contaminants_json_path)

    print("\n10) get_stations_measuring_contaminant")
    print("Stations measuring code 10 in 2019:", station_manager.get_stations_measuring_contaminant(10, 2019))
    print("Stations measuring code 999 in 2021:", station_manager.get_stations_measuring_contaminant(999, 2021))

    print("\n11) get_all_data")
    all_data = station_manager.get_all_data()
    pp.pprint(all_data)

    print("\nManual test completed.")


if __name__ == "__main__":
    main()
